/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monito;

import java.awt.event.KeyEvent;

/**
 *
 * @author RubenEduardo
 */
public class Int_mon extends javax.swing.JFrame {

    /**
     * Creates new form Int_mon
     */
    public Int_mon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nave = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 350));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        nave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/extraterrestre-en-nave-espacial_135.png"))); // NOI18N
        nave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nave.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        getContentPane().add(nave);
        nave.setBounds(260, 90, 125, 98);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int paso = 10;
         if (evt.getKeyCode() == KeyEvent.VK_RIGHT ) {
            //System.out.println(nave.getX()+","+nave.getY());
            nave.setLocation(nave.getX()+paso, nave.getY());
    } else if (evt.getKeyCode() == KeyEvent.VK_LEFT ) {
            //System.out.println(nave.getX()+","+nave.getY());
            nave.setLocation(nave.getX()-paso, nave.getY());
    } else if (evt.getKeyCode() == KeyEvent.VK_UP ) {
            //System.out.println(nave.getX()+","+nave.getY());
            nave.setLocation(nave.getX(), nave.getY()-paso);
    } else if (evt.getKeyCode() == KeyEvent.VK_DOWN ) {
            //System.out.println(nave.getX()+","+nave.getY());
            nave.setLocation(nave.getX(), nave.getY()+paso);
    }
    }//GEN-LAST:event_formKeyPressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Int_mon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Int_mon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Int_mon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Int_mon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nave;
    // End of variables declaration//GEN-END:variables

    private void printf(String hola) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
